### PR TITLE
Tokio-core interop

### PR DESCRIPTION
**Pull request by jrobsonchase**
This provides implementations of Spawn/Executor for Remote/Core
respectively.

### CODE REVIEW

**Comment by sile** [comment]
I saw this PR, but there are two concerns.

### 1

`fibers` provides own [task scheduler](https://github.com/dwango/fibers-rs/blob/master/src/fiber/schedule.rs) and [I/O poller](https://github.com/dwango/fibers-rs/blob/master/src/internal/io_poll/poller.rs).

And the efficiency of the program that uses `fibers` highly depdens on the behaviour of those.

So simple replacement by `tokio_core` may cause performance degradation.
(i.e., All I/O events are watched by busy loops)

### 2

I tried using `tokio_core::reactor::Core` in `examples/tcp_example.rs` as a test.

But the compilation is failed by the following errors:

```sh
$ cargo build --example tcp_example
   Compiling fibers v0.1.6 (file:///home/ohta/dev/rust/pr/fibers-rs)
error[E0277]: the trait bound `for<'r> futures::AndThen<futures::MapErr<fibers::net::futures::Connected, [closure@examples/tcp_example.rs:29:49: 29:70]>, futures::Map<futures::MapErr<handy_async::io::futures::WriteAll<fibers::net::TcpStream, &[u8; 12]>, [closure@examples/tcp_ex\
ample.rs:31:38: 31:59]>, [closure@examples/tcp_example.rs:32:34: 32:40]>, [closure@examples/tcp_example.rs:29:81: 33:22]>: std::ops::FnOnce<(&'r tokio_core::reactor::Handle,)>` is not satisfied
  --> examples/tcp_example.rs:29:28
   |
29 |                     handle.spawn(client.map_err(|e| panic!("{:?}", e)).and_then(|client| {
   |                            ^^^^^ the trait `for<'r> std::ops::FnOnce<(&'r tokio_core::reactor::Handle,)>` is not implemented for `futures::AndThen<futures::MapErr<fibers::net::futures::Connected, [closure@examples/tcp_example.rs:29:49: 29:70]>, futures::Map<futures::MapErr\
<handy_async::io::futures::WriteAll<fibers::net::TcpStream, &[u8; 12]>, [closure@examples/tcp_example.rs:31:38: 31:59]>, [closure@examples/tcp_example.rs:32:34: 32:40]>, [closure@examples/tcp_example.rs:29:81: 33:22]>`

error[E0277]: the trait bound `for<'r> futures::MapErr<futures::AndThen<fibers::net::futures::TcpListenerBind, futures::stream::ForEach<fibers::net::streams::Incoming, [closure@examples/tcp_example.rs:27:27: 35:18 handle:_], std::result::Result<(), std::io::Error>>, [closure@ex\
amples/tcp_example.rs:22:19: 36:10 addr_tx:_, handle:_]>, [closure@examples/tcp_example.rs:37:18: 37:39]>: std::ops::FnOnce<(&'r tokio_core::reactor::Handle,)>` is not satisfied
  --> examples/tcp_example.rs:21:23
   |
21 |     executor.remote().spawn(TcpListener::bind("127.0.0.1:0".parse().unwrap())
   |                       ^^^^^ the trait `for<'r> std::ops::FnOnce<(&'r tokio_core::reactor::Handle,)>` is not implemented for `futures::MapErr<futures::AndThen<fibers::net::futures::TcpListenerBind, futures::stream::ForEach<fibers::net::streams::Incoming, [closure@examples/t\
cp_example.rs:27:27: 35:18 handle:_], std::result::Result<(), std::io::Error>>, [closure@examples/tcp_example.rs:22:19: 36:10 addr_tx:_, handle:_]>, [closure@examples/tcp_example.rs:37:18: 37:39]>`

error: aborting due to 2 previous errors

error: Could not compile `fibers`.

To learn more, run the command again with --verbose.
```

Source code:

```rust
// examples/tcp_example.rs
extern crate fibers;
extern crate futures;
extern crate handy_async;
extern crate tokio_core;  // added

use fibers::{Spawn, Executor};
use fibers::net::{TcpListener, TcpStream};
use fibers::sync::oneshot;
use futures::{Future, Stream};
use handy_async::io::{AsyncWrite, AsyncRead};

fn main() {
    let mut executor = tokio_core::reactor::Core::new().unwrap(); // modofied
    let handle = Executor::handle(&executor);
    let (addr_tx, addr_rx) = oneshot::channel();

    // Spawns TCP listener
    executor.remote().spawn(TcpListener::bind("127.0.0.1:0".parse().unwrap()) // modified
        .and_then(|listener| {
            let addr = listener.local_addr().unwrap();
            println!("# Start listening: {}", addr);
            addr_tx.send(addr).unwrap();
            listener.incoming()
                .for_each(move |(client, addr)| {
                    println!("# Accepted: {}", addr);
                    handle.spawn(client.map_err(|e| panic!("{:?}", e)).and_then(|client| {
                        client.async_write_all(b"Hello World!")
                            .map_err(|e| panic!("{:?}", e))
                            .map(|_| ())
                    }));
                    Ok(())
                })
        })
        .map_err(|e| panic!("{:?}", e)));

    // Spawns TCP client
    let mut monitor = executor.remote().spawn_monitor(addr_rx.map_err(|e| panic!("{:?}", e)) // modified
        .and_then(|server_addr| {
            TcpStream::connect(server_addr).and_then(move |stream| {
                println!("# Connected: {}", server_addr);
                stream.async_read(vec![0; 32])
                    .map(|(_, mut buf, size)| {
                        buf.truncate(size);
                        assert_eq!(buf, b"Hello World!");
                    })
                    .map_err(|e| panic!("{:?}", e))
            })
        }));

    // Runs until the TCP client exits
    while monitor.poll().unwrap().is_not_ready() {
        executor.run_once().unwrap();
    }
    println!("# Succeeded");
}
```

**Comment by jrobsonchase** [comment]
The compilation failure is a result of overlapping definitions for the `spawn` method - it would seem that the non-`Spawn`-trait method is taking precedence. It works if you call the trait method explicitly:

```
// examples/tcp_example.rs
extern crate fibers;
extern crate futures;
extern crate handy_async;
extern crate tokio_core; // added

use fibers::{Spawn, Executor};
use fibers::net::{TcpListener, TcpStream};
use fibers::sync::oneshot;
use futures::{Future, Stream};
use handy_async::io::{AsyncWrite, AsyncRead};

fn main() {
    let mut executor = tokio_core::reactor::Core::new().unwrap(); // modofied
    let handle = Executor::handle(&executor);
    let (addr_tx, addr_rx) = oneshot::channel();

    // Spawns TCP listener
    Spawn::spawn(&executor.remote(),
                 TcpListener::bind("127.0.0.1:0".parse().unwrap()) // modified
        .and_then(|listener| {
            let addr = listener.local_addr().unwrap();
            println!("# Start listening: {}", addr);
            addr_tx.send(addr).unwrap();
            listener.incoming()
                .for_each(move |(client, addr)| {
                    println!("# Accepted: {}", addr);
                    Spawn::spawn(&handle, client.map_err(|e| panic!("{:?}", e)).and_then(|client| {
                        client.async_write_all(b"Hello World!")
                            .map_err(|e| panic!("{:?}", e))
                            .map(|_| ())
                    }));
                    Ok(())
                })
        })
        .map_err(|e| panic!("{:?}", e)));

    // Spawns TCP client
    let mut monitor = executor
        .remote()
        .spawn_monitor(addr_rx.map_err(|e| panic!("{:?}", e)) // modified
        .and_then(|server_addr| {
            TcpStream::connect(server_addr).and_then(move |stream| {
                println!("# Connected: {}", server_addr);
                stream.async_read(vec![0; 32])
                    .map(|(_, mut buf, size)| {
                        buf.truncate(size);
                        assert_eq!(buf, b"Hello World!");
                    })
                    .map_err(|e| panic!("{:?}", e))
            })
        }));

    // Runs until the TCP client exits
    while monitor.poll().unwrap().is_not_ready() {
        executor.run_once().unwrap();
    }
    println!("# Succeeded");
}
```

Obviously not ideal though. Maybe a better option would be to wrap it in a tuple struct?

> fibers provides own task scheduler and I/O poller

It's my understanding that tokio's `Core` brings along its own implementation of IO polling and task scheduling as well.

**Comment by sile** [comment]
> The compilation failure is a result of overlapping definitions for the spawn method.

I see, thanks!

The above code was compiled successfully, but unfortunately, it's execution was aborted by the following error: 

```sh
$ cargo run --example tcp_example
   Compiling fibers v0.1.6 (file:///home/ohta/dev/rust/pr/fibers-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.19 secs
     Running `target/debug/examples/tcp_example`
thread 'main' panicked at '[src/net/mod.rs:63] "fiber::with_current_context(|mut c| c.poller().register(socket))" must be a Some(..)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
```

I remembered that network related futures which provided by `fibers` need to be polled in the context of the `fibers::fiber::Scheduler`.

Therefore, it seems difficult to easily support `tokio-core` (at least in the current version of `fibers`).

**Comment by sile** [comment]
Since a long period of time elapsed without no reaction, I will close this PR.

**Pull request closed without merging**
